baseURL = "http://www.example.com"
title = "Geowarin"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = "geowarin"
googleAnalytics = "UA-46024908-1"

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "A coder's blog"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "geowarin"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideSocialMenu = false
showReadingTime = true
taxonomyCloudShuffle = true

[params.sidebar]
enable = false
sticky = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about", "taxonomy_cloud"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
# codepen = "geowarin"
# email = "contact@example.com"
# facebook = "geowarin"
github = "geowarin"
# gitlab = "geowarin"
# instagram = "geowarin"
linkedin = "muniftanjim"
twitter = "geowarin"
# telegram = "geowarin"
# google_scholar = "qc6CJjYAAAAJ"

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","gitlab","linkedin","telegram","google_scholar"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"
post = "/:title/"

[[menu.main]]
name = "Blog"
weight = -30
identifier = "blog"
url = "/"

[[menu.main]]
name = "Archive"
weight = -20
identifier = "archive"
url = "/archive"

[[menu.main]]
name = "Book"
weight = -10
identifier = "book"
url = "/mastering-spring-mvc-4"

[[menu.main]]
name = "Repo"
weight = 0
identifier = "repository"
url = "https://github.com/geowarin/geowarin.github.com"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
